server:
  port: 8088
api:
  prefix: api/v1
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopapp
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
#    file upload size
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
